import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profileImg from '../../public/dev1.png';
import AnimatedTitle from '@/components/AnimatedTitle';
import Link from 'next/link';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </Head>
            <div className='flex items-center text-dark w-full min-h-screen'>
                <Layout className='pt-0'>
                    <div className='flex items-center justify-between w-full gap-10'>
                        <div className='w-1/2'>
                            <Image
                                src={profileImg}
                                alt='Developer profile image'
                                className='w-full h-auto'
                            />
                        </div>
                        <div className='w-1/2 flex flex-col items-center self-center'>
                            <AnimatedTitle
                                text='Turning Vision Into Reality'
                                className='!text-6xl !text-left'
                            />
                            <p className='my-4 text-base font-medium'>
                                As a skilled full-stack developer, I am
                                dedicated to turning ideas into innovative web
                                applications. Explore my latest projects and
                                articles, showcasing my expertise in React.js
                                and web development.
                            </p>
                            <div className='flex items-center self-start mt-2'>
                                <Link
                                    href='/'
                                    target={'_blank'}
                                    className='flex items-center bg-slate-900 text-light p-1.5 px-6 rounded-lg text-lg font-semibolg hover:bg-light hover:text-slate-900 border-2 border-solid border-transparent hover:border-slate-900 transition-all duration-500'>
                                    Resume
                                </Link>
                                <Link
                                    href='mailto:youzhny.foto@gmail.com'
                                    target={'_blank'}
                                    className='ml-4 text-lg font-medium capitalize text-slate-900 underline'>
                                    Send Email
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
            </div>
        </>
    );
}
